# Generated by Django 2.0.5 on 2018-05-17 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('author_img', models.FileField(upload_to='')),
                ('author_description', models.TextField(default='I am an author that live in Nigeria.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(help_text='Enter the post name', max_length=100)),
                ('post_message', models.TextField(help_text='Enter the post details', max_length=3000)),
                ('post_img', models.FileField(upload_to='')),
                ('post_date', models.DateField(blank=True, null=True)),
                ('post_highlight', models.TextField(help_text='Highlight of your post e.g Trump, we have to stop rocket man', max_length=400, null=True)),
                ('post_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Author')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
